name: RSI Crypto Alert

on:
  # schedule:
  # Chạy tự động mỗi 10 phút một lần
  #  - cron: '*/10 * * * *'
  # Cho phép bấm nút chạy thủ công để test bất kỳ lúc nào
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHAT_ID_LONG: ${{ secrets.TELEGRAM_CHAT_ID_LONG }}
          TELEGRAM_CHAT_ID_RSI_BOT_STATUS: ${{ secrets.TELEGRAM_CHAT_ID_RSI_BOT_STATUS }}
          TELEGRAM_CHAT_ID_RSI_WEEK: ${{ secrets.TELEGRAM_CHAT_ID_RSI_WEEK }} 
          GOOGLE_SHEET_WEBHOOK_URL: ${{ secrets.GOOGLE_SHEET_WEBHOOK_URL }} 
        run: |
          # 1. Luôn chạy bộ quét nhanh 5 phút
          python scanner.py

          # 2. Lấy số phút hiện tại theo giờ UTC (từ 0 đến 59)
          # MINUTE=$(date -u +%-M)

          # Điều kiện: Chạy vào mốc đầu giờ (:00 - :04)
          HOUR=$(date -u +%-H)
          MINUTE=$(date -u +%-M)
          if [ "$MINUTE" -lt 5 ] && [ $((HOUR % 1)) -eq 0 ]; then
            python scan_patterns_hourly.py
          fi
